### PR TITLE
Added curved wall victims and fixed non-reachable tiles

### PR DESCRIPTION
**Pull request by jeffcheng1230**
For rescue simulation, users are now able to add victims onto curved walls. To do so:
Add a curved wall to a tile, and place a victim in the same quarter-tile as if it were being placed on a half wall. The program will recognize that a victim is in the same quarter-tile as a curved wall, and automatically stick the victim onto the curved wall. If the victim is placed on the inside of the wall, it will stick on the inside of the curved wall. If the victim is placed on the outside of the wall and still in the same quarter-tile, it will stick on the outside of the curved wall.

Previously, the code was not complete when considering half-walls and curved walls in its search to determine which tiles were impossible to visit. This is now fixed.

### CODE REVIEW

**Comment by rrrobo** [comment]
Hi,
Thank you for your PR.
Before reviewing, cloud you please clean up your commits?
The project's .gitignore and previous commits were not so good, but there is no need to commit for any files other than public/javascripts/sim_editor.2021.js.

Thank you

**Comment by rrrobo** [comment]
Hi,
For a design like this, I think
sc1
 the tile at the center of the top should be marked as reachable, what do you think?

**Comment by jeffcheng1230** [comment]
Yes, I agree. I will change it.
In general though, say that tile had a full right wall, should it still be
marked as unreachable? (there is that little gap in the right half of the
bottom wall, but no robot could fit through that)

**Comment by rrrobo** [comment]
I think you are basically correct, but you may need to check the rules. If the rule says that the competition area must be surrounded by a wall, it would be incorrect.
But anyway, in this time, it would be easy to mark it as unreachable if it is "completely blocked" by walls. If it is marked as unreachable, no floor is created for that tile, which lead a major issue, but even if the system marks unreachable in normal way (ex, only half the tile is open) as reachable in mistake, there will be no practical problem.

**Comment by rrrobo** [comment]
LGTM

**Pull request merged**
